-- ==========================================
-- VIZIER Academy - Seed Data (008_rag_seed)
-- ==========================================

-- 1. SEED DICTIONARY TERMS FOR PHASE 7 (BLOCK 7.1)
INSERT INTO dictionary_terms (term, category, beginner_definition, deep_definition, analogy, related_terms, first_seen_phase) VALUES
('embedding dimension', 'Embeddings',
 'The number of values (dimensions) in a single vector that represents the meaning of a text (e.g. Gemini uses 768 dimensions).',
 'The length of the dense numerical vector generated by an embedding model representing semantic features in a high-dimensional vector space.',
 'The number of coordinates required to locate a point in space. 3D requires 3 coordinates (X, Y, Z); Gemini RAG requires 768 coordinates.',
 ARRAY['vector', 'embedding'], 'Phase 7'),

('HNSW', 'Embeddings',
 'A super-fast index structure that connects similar vectors together like a social network, making searches take milliseconds.',
 'Hierarchical Navigable Small World: a graph-based algorithm for approximate nearest neighbor (ANN) vector search, scaling logarithmically.',
 'A roadmap connecting cities. Instead of checking every house in the country, you take highways to the right state first, then local roads.',
 ARRAY['vector database', 'embedding'], 'Phase 7'),

('hybrid search', 'Retrieval',
 'Combining keyword search (matching exact words) with vector search (matching meanings) to get the most accurate results.',
 'A search pipeline combining dense vector similarity search (representing semantics) with sparse keyword retrieval (e.g. BM25/tsvector).',
 'A librarian who looks up books using both the exact card catalog index (keywords) and by browsing shelves in similar topic sections (meaning).',
 ARRAY['RRF', 'vector'], 'Phase 7'),

('RRF', 'Retrieval',
 'Reciprocal Rank Fusion: A scoring method that combines results from two different search lists into one perfect list.',
 'Reciprocal Rank Fusion: a rank aggregation algorithm that scores documents based on their inverse rank in multiple source lists.',
 'A movie aggregator like Rotten Tomatoes combining critic scores and audience scores into a single top-10 list.',
 ARRAY['hybrid search'], 'Phase 7'),

('reranker', 'Retrieval',
 'A secondary, smarter AI model that reviews a list of search results and re-orders them to put the absolute best match at the very top.',
 'A cross-encoder model that evaluates query-document pairs to predict precise relevance scores, correcting initial retriever rank errors.',
 'A chief editor reviewing a reporter''s draft pile to pick the absolute best story for the front page layout.',
 ARRAY['hybrid search', 'RRF'], 'Phase 7'),

('chunk overlap', 'Ingestion',
 'A small slice of text copied from the end of one chunk to the start of the next, preventing sentences from being cut in half.',
 'The token or character redundancy maintained between consecutive document segments to preserve contextual boundaries across chunks.',
 'Overlap in roof tiles. If they didn''t overlap slightly, rain would leak through the cracks between the tiles.',
 ARRAY['ingestion'], 'Phase 7'),

('ingestion', 'Ingestion',
 'The process of reading files, slicing them into pieces (chunks), generating vectors, and saving them to your database.',
 'The ETL pipeline responsible for parsing raw document formats, segmenting content, generating embeddings, and indexing them in a database.',
 'Dismantling a book index, copying paragraphs onto index cards, indexing them by topic, and filing them in cabinets.',
 ARRAY['chunk overlap'], 'Phase 7')
ON CONFLICT (term) DO NOTHING;

-- 2. SEED LESSONS FOR PHASE 7 (BLOCK 7.1)
INSERT INTO lessons (phase, order_index, title, body_markdown, competency_tag) VALUES
(7, 1, 'pgvector RAG Pipelines & Hybrid Search',
 '# Lesson 7.1: Retrieval-Augmented Generation & Vector Geometry

In this block, we built a production-grade **Retrieval-Augmented Generation (RAG)** pipeline using **pgvector** in Supabase PostgreSQL.

### Why pgvector?
Running RAG requires storing text segments alongside dense mathematical representations of their meanings (embeddings). By using pgvector inside Postgres:
- We keep metadata (documents, audit logs) and embeddings in the same relational database.
- We run standard SQL queries for vector similarity.
- We leverage PostgreSQL GIN indexes alongside HNSW vector graphs.

### The Mechanics of Hybrid Retrieval
Standard vector search can fail on exact keyword match requirements (e.g. searching for a code function name like `parse_db_url_to_dsn`). Full-text keyword search can fail on semantic intent (e.g. searching for "durable memory" matching "checkpointer").

By running **Hybrid Search**, we get the best of both worlds:
1. **Vector search:** Cosine similarity distance (`<=>` operator) on HNSW index.
2. **Keyword search:** `tsvector` query matching on GIN index.
3. **Merging (RRF):** Combine rankings using Reciprocal Rank Fusion, putting documents that rank highly in BOTH lists at the top.

### Ingestion Pipeline
To feed documents, we load files (Markdown, Plain Text, PDFs), slice them into ~800 character chunks with ~100 character overlap to maintain context boundaries, query Gemini''s `text-embedding-004` (768 dimensions), and write them to Supabase.',
 'pgvector_rag_rrf')
ON CONFLICT (phase, order_index) DO NOTHING;
